<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <customApplicationComponents>
        <alignment>right</alignment>
    </customApplicationComponents>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <description>Application for LIVESPORT agents to support their customers.</description>
    <detailPageRefreshMethod>autoRefresh</detailPageRefreshMethod>
    <enableCustomizeMyTabs>false</enableCustomizeMyTabs>
    <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
    <enableListViewHover>true</enableListViewHover>
    <enableListViewReskin>true</enableListViewReskin>
    <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
    <enablePinTabs>true</enablePinTabs>
    <enableTabHover>false</enableTabHover>
    <enableTabLimits>false</enableTabLimits>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <keyboardShortcuts>
        <defaultShortcut>
            <action>FOCUS_CONSOLE</action>
            <active>true</active>
            <keyCommand>ESC</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_NAVIGATOR_TAB</action>
            <active>true</active>
            <keyCommand>V</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_DETAIL_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_PRIMARY_TAB_PANEL</action>
            <active>true</active>
            <keyCommand>P</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SUBTAB_PANEL</action>
            <active>true</active>
            <keyCommand>S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FIRST_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SEARCH_INPUT</action>
            <active>true</active>
            <keyCommand>R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_LEFT</action>
            <active>true</active>
            <keyCommand>LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_RIGHT</action>
            <active>true</active>
            <keyCommand>RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>UP_ARROW</action>
            <active>true</active>
            <keyCommand>UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>DOWN_ARROW</action>
            <active>true</active>
            <keyCommand>DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB_SCROLLER_MENU</action>
            <active>true</active>
            <keyCommand>D</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB</action>
            <active>true</active>
            <keyCommand>T</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CLOSE_TAB</action>
            <active>true</active>
            <keyCommand>C</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REFRESH_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>ENTER</action>
            <active>true</active>
            <keyCommand>ENTER</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>EDIT</action>
            <active>true</active>
            <keyCommand>E</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>SAVE</action>
            <active>true</active>
            <keyCommand>CTRL+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CONSOLE_LINK_DIALOG</action>
            <active>false</active>
            <keyCommand>U</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>HOTKEYS_PANEL</action>
            <active>false</active>
            <keyCommand>SHIFT+K</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_MACRO</action>
            <active>false</active>
            <keyCommand>M</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FOOTER_PANEL</action>
            <active>false</active>
            <keyCommand>F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LIST_VIEW</action>
            <active>false</active>
            <keyCommand>SHIFT+N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LEFT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_RIGHT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_TOP_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_BOTTOM_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
            <active>false</active>
            <keyCommand>Z</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REOPEN_LAST_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+C</keyCommand>
        </defaultShortcut>
    </keyboardShortcuts>
    <label>LIVESPORT</label>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>refreshList</listRefreshMethod>
    <liveAgentConfig>
        <enableLiveChat>true</enableLiveChat>
        <openNewAccountSubtab>false</openNewAccountSubtab>
        <openNewCaseSubtab>true</openNewCaseSubtab>
        <openNewContactSubtab>false</openNewContactSubtab>
        <openNewLeadSubtab>false</openNewLeadSubtab>
        <openNewVFPageSubtab>false</openNewVFPageSubtab>
        <showKnowledgeArticles>true</showKnowledgeArticles>
    </liveAgentConfig>
    <saveUserSessions>true</saveUserSessions>
    <tab>standard-home</tab>
    <tab>standard-Account</tab>
    <tab>standard-Case</tab>
    <tab>standard-Knowledge</tab>
    <tab>standard-KnowledgePublishing</tab>
    <tab>standard-LiveAgentSupervisor</tab>
    <tab>User_Devices__c</tab>
    <tab>Email_Help_Option__c</tab>
    <tab>Custom_Provider__c</tab>
    <tab>DAZNUserFeed__c</tab>
    <tab>DAZN_Events_Calendar__c</tab>
    <tab>Email_Sync_Queue__c</tab>
    <tab>API_Log__c</tab>
    <tab>Gift_Code_History__c</tab>
    <workspaceMappings>
        <mapping>
            <tab>API_Log__c</tab>
        </mapping>
        <mapping>
            <tab>Custom_Provider__c</tab>
        </mapping>
        <mapping>
            <tab>DAZNUserFeed__c</tab>
        </mapping>
        <mapping>
            <tab>DAZN_Events_Calendar__c</tab>
        </mapping>
        <mapping>
            <tab>Email_Help_Option__c</tab>
        </mapping>
        <mapping>
            <tab>Email_Sync_Queue__c</tab>
        </mapping>
        <mapping>
            <tab>Gift_Code_History__c</tab>
        </mapping>
        <mapping>
            <tab>User_Devices__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>standard-Knowledge</tab>
        </mapping>
        <mapping>
            <tab>standard-KnowledgePublishing</tab>
        </mapping>
        <mapping>
            <tab>standard-LiveAgentSupervisor</tab>
        </mapping>
        <mapping>
            <tab>standard-home</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
