/**
* @author Cognizant Technology Solutuions
* @date 18/04/2016
* @description class to schedule account update in communicator.
*/
global class scheduleDoubleOptin implements Schedulable {
   global void execute(SchedulableContext SC) {
        //BatchTriggerDoubleOptin NotifyBatch  = new BatchTriggerDoubleOptin();
        //ID batchprocessid = Database.executeBatch(NotifyBatch, 200);      
   }
}