/**
* @author Cognizant Technology Solutuions
* @date 18/04/2016
* @description class to schedule account update in communicator.
*/
global class scheduleAccountUpsertInCommunicator implements Schedulable {
   global void execute(SchedulableContext SC) {
       //BatchUpsertAccountsInCommunicator NotifyBatch  = new BatchUpsertAccountsInCommunicator();
       //ID batchprocessid = Database.executeBatch(NotifyBatch, 50);      
   }
}